# [build-system]
# requires = ["setuptools", "setuptools-scm"]
# build-backend = "setuptools.build_meta"

[project]
version = "0.0.1"
name = "cloudfront-s3-sign"
dependencies = [
  "cryptography", "botocore"
]